# Generated by Django 6.1.1 on 2026-09-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bk_cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
